general_cfg:
    algo_name: PPO
    device: cuda:1
    env_name: LoadVideo-v0
    eval_eps: 10
    eval_per_episode: 5
    load_checkpoint: true
    load_path: Train_LoadVideo-v0_PPO_20230112-142607
    max_steps: 100
    mode: test
    save_fig: true
    seed: 0
    show_fig: false
    test_eps: 10
    train_eps: 100
algo_cfg:
    actor_hidden_dim: 128
    actor_lr: 0.0001
    batch_size: 5
    continuous: false
    critic_hidden_dim: 128
    critic_lr: 0.001
    gae_lambda: 0.95
    gamma: 0.95
    n_epochs: 4
    policy_clip: 0.2
    update_fre: 20
