general_cfg:
    algo_name: PPO
    render: false
    new_step_api: true
    continuous: false
    device: cuda:1
    env_name: LoadVideo-v0
    eval_eps: 10
    eval_per_episode: 5
    load_checkpoint: false
    load_path: tasks
    max_steps: 100
    mode: train
    save_fig: true
    seed: 0
    show_fig: false
    test_eps: 10
    train_eps: 100
    wrapper: null
algo_cfg:
    ppo_type: clip
    actor_hidden_dim: 256
    actor_lr: 0.0003
    critic_hidden_dim: 256
    critic_lr: 0.001
    entropy_coef: 0.01
    eps_clip: 0.2
    gamma: 0.95
    k_epochs: 4
    train_batch_size: 100
